---
title: "Profiling 5"
author: "mhv"
date: "12/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(scales)
library(tidyverse)

source("/Users/mhvpbp13/git/rsystrade/R/benchmark.R")
```



# Test 1
*******************************************************
WARNING:

This takes many, MANY hours to run! Even days...

See "Profiling-5-2.html"
*******************************************************
## Define functions to be tested
```{r}
version1 <- function(df) {
  var1 <- 0
  var2 <- 0
  var3 <- 0
  var4 <- 0
  var5 <- 0
  var6 <- 0
  var7 <- 0
  var8 <- 0
  var9 <- 0
  var10 <- 0
  var11 <- 0
  var12 <- 0
  var13 <- 0
  var14 <- 0
  var15 <- 0
  var16 <- 0
  var17 <- 0
  var18 <- 0
  var19 <- 0
  var20 <- 0
  
  v1f1 <- function(n) {var1 <<- df[n-1, 1]}
  v1f2 <- function(n) {var2 <<- df[n-1, 2] + log(var1)}
  v1f3 <- function(n) {var3 <<- df[n-1, 3] + log(var2)}
  v1f4 <- function(n) {var4 <<- df[n-1, 4] + log(var3)}
  v1f5 <- function(n) {var5 <<- df[n-1, 5] + log(var4)}
  v1f6 <- function(n) {var6 <<- df[n-1, 6] + log(var5)}
  v1f7 <- function(n) {var7 <<- df[n-1, 7] + log(var6)}
  v1f8 <- function(n) {var8 <<- df[n-1, 8] + log(var7)}
  v1f9 <- function(n) {var9 <<- df[n-1, 9] + log(var8)}
  v1f10 <- function(n) {var10 <<- df[n-1, 10] + log(var9)}
  v1f11 <- function(n) {var11 <<- df[n-1, 11] + log(var10)}
  v1f12 <- function(n) {var12 <<- df[n-1, 12] + log(var11)}
  v1f13 <- function(n) {var13 <<- df[n-1, 13] + log(var12)}
  v1f14 <- function(n) {var14 <<- df[n-1, 14] + log(var13)}
  v1f15 <- function(n) {var15 <<- df[n-1, 15] + log(var14)}
  v1f16 <- function(n) {var16 <<- df[n-1, 16] + log(var15)}
  v1f17 <- function(n) {var17 <<- df[n-1, 17] + log(var16)}
  v1f18 <- function(n) {var18 <<- df[n-1, 18] + log(var17)}
  v1f19 <- function(n) {var19 <<- df[n-1, 19] + log(var18)}
  v1f20 <- function(n) {var20 <<- df[n-1, 20] + log(var19)}

  for(n in 2:nrow(df)) {
    var1 <- v1f1(n)
    var2 <- v1f2(n)
    var3 <- v1f3(n)
    var4 <- v1f4(n)
    var5 <- v1f5(n)
    var6 <- v1f6(n)
    var7 <- v1f7(n)
    var8 <- v1f8(n)
    var9 <- v1f9(n)
    var10 <- v1f10(n)
    var11 <- v1f11(n)
    var12 <- v1f12(n)
    var13 <- v1f13(n)
    var14 <- v1f14(n)
    var15 <- v1f15(n)
    var16 <- v1f16(n)
    var17 <- v1f17(n)
    var18 <- v1f18(n)
    var19 <- v1f19(n)
    var20 <- v1f20(n)
    
    df[n, ] <- c(
      var1,
      var2,
      var3,
      var4,
      var5,
      var6,
      var7,
      var8,
      var9,
      var10,
      var11,
      var12,
      var13,
      var14,
      var15,
      var16,
      var17,
      var18,
      var19,
      var20
    )
  }

  df
}

v2f1 <- function(n, df) {df[n-1, 1]}
v2f2 <- function(n, df, var) {df[n-1, 2] + log(var)}
v2f3 <- function(n, df, var) {df[n-1, 3] + log(var)}
v2f4 <- function(n, df, var) {df[n-1, 4] + log(var)}
v2f5 <- function(n, df, var) {df[n-1, 5] + log(var)}
v2f6 <- function(n, df, var) {df[n-1, 6] + log(var)}
v2f7 <- function(n, df, var) {df[n-1, 7] + log(var)}
v2f8 <- function(n, df, var) {df[n-1, 8] + log(var)}
v2f9 <- function(n, df, var) {df[n-1, 9] + log(var)}
v2f10 <- function(n, df, var) {df[n-1, 10] + log(var)}
v2f11 <- function(n, df, var) {df[n-1, 11] + log(var)}
v2f12 <- function(n, df, var) {df[n-1, 12] + log(var)}
v2f13 <- function(n, df, var) {df[n-1, 13] + log(var)}
v2f14 <- function(n, df, var) {df[n-1, 14] + log(var)}
v2f15 <- function(n, df, var) {df[n-1, 15] + log(var)}
v2f16 <- function(n, df, var) {df[n-1, 16] + log(var)}
v2f17 <- function(n, df, var) {df[n-1, 17] + log(var)}
v2f18 <- function(n, df, var) {df[n-1, 18] + log(var)}
v2f19 <- function(n, df, var) {df[n-1, 19] + log(var)}
v2f20 <- function(n, df, var) {df[n-1, 20] + log(var)}

version2 <- function(df) {
  
  for(n in 2:nrow(df)) {
    var1 <- v2f1(n, df)
    var2 <- v2f2(n, df, var1)
    var3 <- v2f3(n, df, var2)
    var4 <- v2f4(n, df, var3)
    var5 <- v2f5(n, df, var4)
    var6 <- v2f6(n, df, var5)
    var7 <- v2f7(n, df, var6)
    var8 <- v2f8(n, df, var7)
    var9 <- v2f9(n, df, var8)
    var10 <- v2f10(n, df, var9)
    var11 <- v2f11(n, df, var10)
    var12 <- v2f12(n, df, var11)
    var13 <- v2f13(n, df, var12)
    var14 <- v2f14(n, df, var13)
    var15 <- v2f15(n, df, var14)
    var16 <- v2f16(n, df, var15)
    var17 <- v2f17(n, df, var16)
    var18 <- v2f18(n, df, var17)
    var19 <- v2f19(n, df, var18)
    var20 <- v2f20(n, df, var19)
    
    df[n, ] <- c(
      var1,
      var2,
      var3,
      var4,
      var5,
      var6,
      var7,
      var8,
      var9,
      var10,
      var11,
      var12,
      var13,
      var14,
      var15,
      var16,
      var17,
      var18,
      var19,
      var20
    )
  }

  df
}

version3 <- function(df) {
  
  v3f1 <- function(n, df) {df[n-1, 1]}
  v3f2 <- function(n, df, var) {df[n-1, 2] + log(var)}
  v3f3 <- function(n, df, var) {df[n-1, 3] + log(var)}
  v3f4 <- function(n, df, var) {df[n-1, 4] + log(var)}
  v3f5 <- function(n, df, var) {df[n-1, 5] + log(var)}
  v3f6 <- function(n, df, var) {df[n-1, 6] + log(var)}
  v3f7 <- function(n, df, var) {df[n-1, 7] + log(var)}
  v3f8 <- function(n, df, var) {df[n-1, 8] + log(var)}
  v3f9 <- function(n, df, var) {df[n-1, 9] + log(var)}
  v3f10 <- function(n, df, var) {df[n-1, 10] + log(var)}
  v3f11 <- function(n, df, var) {df[n-1, 11] + log(var)}
  v3f12 <- function(n, df, var) {df[n-1, 12] + log(var)}
  v3f13 <- function(n, df, var) {df[n-1, 13] + log(var)}
  v3f14 <- function(n, df, var) {df[n-1, 14] + log(var)}
  v3f15 <- function(n, df, var) {df[n-1, 15] + log(var)}
  v3f16 <- function(n, df, var) {df[n-1, 16] + log(var)}
  v3f17 <- function(n, df, var) {df[n-1, 17] + log(var)}
  v3f18 <- function(n, df, var) {df[n-1, 18] + log(var)}
  v3f19 <- function(n, df, var) {df[n-1, 19] + log(var)}
  v3f20 <- function(n, df, var) {df[n-1, 20] + log(var)}
  
  for(n in 2:nrow(df)) {
    var1 <- v3f1(n, df)
    var2 <- v3f2(n, df, var1)
    var3 <- v3f3(n, df, var2)
    var4 <- v3f4(n, df, var3)
    var5 <- v3f5(n, df, var4)
    var6 <- v3f6(n, df, var5)
    var7 <- v3f7(n, df, var6)
    var8 <- v3f8(n, df, var7)
    var9 <- v3f9(n, df, var8)
    var10 <- v3f10(n, df, var9)
    var11 <- v3f11(n, df, var10)
    var12 <- v3f12(n, df, var11)
    var13 <- v3f13(n, df, var12)
    var14 <- v3f14(n, df, var13)
    var15 <- v3f15(n, df, var14)
    var16 <- v3f16(n, df, var15)
    var17 <- v3f17(n, df, var16)
    var18 <- v3f18(n, df, var17)
    var19 <- v3f19(n, df, var18)
    var20 <- v3f20(n, df, var19)
    
    df[n, ] <- c(
      var1,
      var2,
      var3,
      var4,
      var5,
      var6,
      var7,
      var8,
      var9,
      var10,
      var11,
      var12,
      var13,
      var14,
      var15,
      var16,
      var17,
      var18,
      var19,
      var20
    )
  }

  df
}

v4f1 <- function(row_n, prev_row) {
  row_n[1] <- prev_row[1]
  row_n
}
v4f2 <- function(row_n, prev_row) {
  row_n[2] <- prev_row[2] + log(row_n[1])
  row_n
}
v4f3 <- function(row_n, prev_row) {
  row_n[3] <- prev_row[3] + log(row_n[2])
  row_n
}
v4f4 <- function(row_n, prev_row) {
  row_n[4] <- prev_row[4] + log(row_n[3])
  row_n
}
v4f5 <- function(row_n, prev_row) {
  row_n[5] <- prev_row[5] + log(row_n[4])
  row_n
}
v4f6 <- function(row_n, prev_row) {
  row_n[6] <- prev_row[6] + log(row_n[5])
  row_n
}
v4f7 <- function(row_n, prev_row) {
  row_n[7] <- prev_row[7] + log(row_n[6])
  row_n
}
v4f8 <- function(row_n, prev_row) {
  row_n[8] <- prev_row[8] + log(row_n[7])
  row_n
}
v4f9 <- function(row_n, prev_row) {
  row_n[9] <- prev_row[9] + log(row_n[8])
  row_n
}
v4f10 <- function(row_n, prev_row) {
  row_n[10] <- prev_row[10] + log(row_n[9])
  row_n
}
v4f11 <- function(row_n, prev_row) {
  row_n[11] <- prev_row[11] + log(row_n[10])
  row_n
}
v4f12 <- function(row_n, prev_row) {
  row_n[12] <- prev_row[12] + log(row_n[11])
  row_n
}
v4f13 <- function(row_n, prev_row) {
  row_n[13] <- prev_row[13] + log(row_n[12])
  row_n
}
v4f14 <- function(row_n, prev_row) {
  row_n[14] <- prev_row[14] + log(row_n[13])
  row_n
}
v4f15 <- function(row_n, prev_row) {
  row_n[15] <- prev_row[15] + log(row_n[14])
  row_n
}
v4f16 <- function(row_n, prev_row) {
  row_n[16] <- prev_row[16] + log(row_n[15])
  row_n
}
v4f17 <- function(row_n, prev_row) {
  row_n[17] <- prev_row[17] + log(row_n[16])
  row_n
}
v4f18 <- function(row_n, prev_row) {
  row_n[18] <- prev_row[18] + log(row_n[17])
  row_n
}
v4f19 <- function(row_n, prev_row) {
  row_n[19] <- prev_row[19] + log(row_n[18])
  row_n
}
v4f20 <- function(row_n, prev_row) {
  row_n[20] <- prev_row[20] + log(row_n[19])
  row_n
}

version4 <- function(df) {
  force(df)
  for(i in 2:nrow(df)) {
    df[i, ] <- df[i, ]  %>%
      v4f1(., prev_row = df[i-1, ]) %>%
      v4f2(., prev_row = df[i-1, ]) %>%
      v4f3(., prev_row = df[i-1, ]) %>%
      v4f4(., prev_row = df[i-1, ]) %>%
      v4f5(., prev_row = df[i-1, ]) %>%
      v4f6(., prev_row = df[i-1, ]) %>%
      v4f7(., prev_row = df[i-1, ]) %>%
      v4f8(., prev_row = df[i-1, ]) %>%
      v4f9(., prev_row = df[i-1, ]) %>%
      v4f10(., prev_row = df[i-1, ]) %>%
      v4f11(., prev_row = df[i-1, ]) %>%
      v4f12(., prev_row = df[i-1, ]) %>%
      v4f13(., prev_row = df[i-1, ]) %>%
      v4f14(., prev_row = df[i-1, ]) %>%
      v4f15(., prev_row = df[i-1, ]) %>%
      v4f16(., prev_row = df[i-1, ]) %>%
      v4f17(., prev_row = df[i-1, ]) %>%
      v4f18(., prev_row = df[i-1, ]) %>%
      v4f19(., prev_row = df[i-1, ]) %>%
      v4f20(., prev_row = df[i-1, ])
  }
  df
}

v5f1 <- function(row_n, prev_row) {
  row_n[1] <- prev_row[1]
  row_n
}
v5f2 <- function(row_n, prev_row) {
  row_n[2] <- prev_row[2] + log(row_n[1])
  row_n
}
v5f3 <- function(row_n, prev_row) {
  row_n[3] <- prev_row[3] + log(row_n[2])
  row_n
}
v5f4 <- function(row_n, prev_row) {
  row_n[4] <- prev_row[4] + log(row_n[3])
  row_n
}
v5f5 <- function(row_n, prev_row) {
  row_n[5] <- prev_row[5] + log(row_n[4])
  row_n
}
v5f6 <- function(row_n, prev_row) {
  row_n[6] <- prev_row[6] + log(row_n[5])
  row_n
}
v5f7 <- function(row_n, prev_row) {
  row_n[7] <- prev_row[7] + log(row_n[6])
  row_n
}
v5f8 <- function(row_n, prev_row) {
  row_n[8] <- prev_row[8] + log(row_n[7])
  row_n
}
v5f9 <- function(row_n, prev_row) {
  row_n[9] <- prev_row[9] + log(row_n[8])
  row_n
}
v5f10 <- function(row_n, prev_row) {
  row_n[10] <- prev_row[10] + log(row_n[9])
  row_n
}
v5f11 <- function(row_n, prev_row) {
  row_n[11] <- prev_row[11] + log(row_n[10])
  row_n
}
v5f12 <- function(row_n, prev_row) {
  row_n[12] <- prev_row[12] + log(row_n[11])
  row_n
}
v5f13 <- function(row_n, prev_row) {
  row_n[13] <- prev_row[13] + log(row_n[12])
  row_n
}
v5f14 <- function(row_n, prev_row) {
  row_n[14] <- prev_row[14] + log(row_n[13])
  row_n
}
v5f15 <- function(row_n, prev_row) {
  row_n[15] <- prev_row[15] + log(row_n[14])
  row_n
}
v5f16 <- function(row_n, prev_row) {
  row_n[16] <- prev_row[16] + log(row_n[15])
  row_n
}
v5f17 <- function(row_n, prev_row) {
  row_n[17] <- prev_row[17] + log(row_n[16])
  row_n
}
v5f18 <- function(row_n, prev_row) {
  row_n[18] <- prev_row[18] + log(row_n[17])
  row_n
}
v5f19 <- function(row_n, prev_row) {
  row_n[19] <- prev_row[19] + log(row_n[18])
  row_n
}
v5f20 <- function(row_n, prev_row) {
  row_n[20] <- prev_row[20] + log(row_n[19])
  row_n
}

version5 <- function(df) {
  force(df)
  for(i in 2:nrow(df)) {
    df[i, ] <- v5f1(df[i, ], df[i-1, ])
    df[i, ] <- v5f2(df[i, ], df[i-1, ])
    df[i, ] <- v5f3(df[i, ], df[i-1, ])
    df[i, ] <- v5f4(df[i, ], df[i-1, ])
    df[i, ] <- v5f5(df[i, ], df[i-1, ])
    df[i, ] <- v5f6(df[i, ], df[i-1, ])
    df[i, ] <- v5f7(df[i, ], df[i-1, ])
    df[i, ] <- v5f8(df[i, ], df[i-1, ])
    df[i, ] <- v5f9(df[i, ], df[i-1, ])
    df[i, ] <- v5f10(df[i, ], df[i-1, ])
    df[i, ] <- v5f11(df[i, ], df[i-1, ])
    df[i, ] <- v5f12(df[i, ], df[i-1, ])
    df[i, ] <- v5f13(df[i, ], df[i-1, ])
    df[i, ] <- v5f14(df[i, ], df[i-1, ])
    df[i, ] <- v5f15(df[i, ], df[i-1, ])
    df[i, ] <- v5f16(df[i, ], df[i-1, ])
    df[i, ] <- v5f17(df[i, ], df[i-1, ])
    df[i, ] <- v5f18(df[i, ], df[i-1, ])
    df[i, ] <- v5f19(df[i, ], df[i-1, ])
    df[i, ] <- v5f20(df[i, ], df[i-1, ])
  }
  df
}

v6f1 <- function(row_n, prev_row) {
  prev_row[1]
}
v6f2 <- function(row_n, prev_row) {
  prev_row[2] + log(row_n[1])
}
v6f3 <- function(row_n, prev_row) {
  prev_row[3] + log(row_n[2])
}
v6f4 <- function(row_n, prev_row) {
  prev_row[4] + log(row_n[3])
}
v6f5 <- function(row_n, prev_row) {
  prev_row[5] + log(row_n[4])
}
v6f6 <- function(row_n, prev_row) {
  prev_row[6] + log(row_n[5])
}
v6f7 <- function(row_n, prev_row) {
  prev_row[7] + log(row_n[6])
}
v6f8 <- function(row_n, prev_row) {
  prev_row[8] + log(row_n[7])
}
v6f9 <- function(row_n, prev_row) {
  prev_row[9] + log(row_n[8])
}
v6f10 <- function(row_n, prev_row) {
  prev_row[10] + log(row_n[9])
}
v6f11 <- function(row_n, prev_row) {
  prev_row[11] + log(row_n[10])
}
v6f12 <- function(row_n, prev_row) {
  prev_row[12] + log(row_n[11])
}
v6f13 <- function(row_n, prev_row) {
  prev_row[13] + log(row_n[12])
}
v6f14 <- function(row_n, prev_row) {
  prev_row[14] + log(row_n[13])
}
v6f15 <- function(row_n, prev_row) {
  prev_row[15] + log(row_n[14])
}
v6f16 <- function(row_n, prev_row) {
  prev_row[16] + log(row_n[15])
}
v6f17 <- function(row_n, prev_row) {
  prev_row[17] + log(row_n[16])
}
v6f18 <- function(row_n, prev_row) {
  prev_row[18] + log(row_n[17])
}
v6f19 <- function(row_n, prev_row) {
  prev_row[19] + log(row_n[18])
}
v6f20 <- function(row_n, prev_row) {
  prev_row[20] + log(row_n[19])
}

version6 <- function(df) {
  force(df)
  row <- df[1, ]
  for(i in 2:nrow(df)) {
    prev_row <- df[i-1, ]
    row[1] <- v6f1(row, prev_row)
    row[2] <- v6f2(row, prev_row)
    row[3] <- v6f3(row, prev_row)
    row[4] <- v6f4(row, prev_row)
    row[5] <- v6f5(row, prev_row)
    row[6] <- v6f6(row, prev_row)
    row[7] <- v6f7(row, prev_row)
    row[8] <- v6f8(row, prev_row)
    row[9] <- v6f9(row, prev_row)
    row[10] <- v6f10(row, prev_row)
    row[11] <- v6f11(row, prev_row)
    row[12] <- v6f12(row, prev_row)
    row[13] <- v6f13(row, prev_row)
    row[14] <- v6f14(row, prev_row)
    row[15] <- v6f15(row, prev_row)
    row[16] <- v6f16(row, prev_row)
    row[17] <- v6f17(row, prev_row)
    row[18] <- v6f18(row, prev_row)
    row[19] <- v6f19(row, prev_row)
    row[20] <- v6f20(row, prev_row)
    df[i, ] <- row
  }
  df
}
```

## Run tests 1a
```{r include=FALSE, eval=FALSE}
f_list <- list(
  version1 = "version1(df)",
  version2 = "version2(df)",
  version3 = "version3(df)",
  version4 = "version4(df)",
  version5 = "version5(df)",
  version6 = "version6(df)"
)
df_1a <- map_df(10^(1:4), run_benchmark, functions = f_list) %>% order_graphs()
```

## Print test data 1a
```{r include=FALSE, eval=FALSE}
plot_bm(df_1a, "nrow")
```


## Run tests 1b: See if version 1 gets slower than version 6 at high number of 
## rows.
```{r}
f_list <- list(
  version1 = "version1(df)",
  #version2 = "version2(df)",
  #version3 = "version3(df)",
  #version4 = "version4(df)",
  #version5 = "version5(df)",
  version6 = "version6(df)"
)
df_1b <- map_df(5 * 10^(2:5), run_benchmark, ncol = 20, functions = f_list) %>% order_graphs()
```

## Print test data 1b
```{r}
plot_bm(df_1b, "nrow")
```


```{r}
#detach("package:microbenchmark", unload=TRUE)
#detach("package:ggplot2", unload=TRUE)
detach("package:tidyverse", unload=TRUE)
#detach("package:purrr", unload=TRUE)
#detach("package:tibble", unload=TRUE)
#detach("package:dplyr", unload=TRUE)
#detach("package:magrittr", unload=TRUE)
```
